# --- Xilinx Vitis IDE Backend ---
#
# Backend hook invoked by ide_generate() (cmake/ide/ide_config.cmake) when
# PLATFORM == "xilinx". It exists to satisfy the backend dispatch contract
# (ide_get_backends() returns "vitis" for Xilinx, and ide_generate() calls
# ide_vitis_configure()/ide_vitis_post_build() for every project target).
#
# Unlike the stm32cubeide/vscode backends, no Vitis (Eclipse) IDE project is
# generated here. The firmware is compiled by CMake itself; the only Vitis
# artifacts the build needs (the standalone BSP libxil + lscript.ld) are
# produced at configure time by cmake/xilinx_platform_sdk.cmake via xsct.
# On-target loading/debug is driven separately by the HIL JTAG loader
# (tests/hil/loaders/) using xsct, not by an in-repo IDE launch config.
#
# Keep these as valid, minimal functions so post_build_config() does not fail
# on Xilinx targets. Extend here if a generated Vitis workspace is ever wanted.

function(ide_vitis_configure PROJECT_TARGET)
    message(STATUS "Vitis IDE backend: no project files generated for "
                   "'${PROJECT_TARGET}' (CMake compiles the firmware; the BSP "
                   "is generated by xilinx_platform_sdk.cmake).")
endfunction()

function(ide_vitis_post_build PROJECT_TARGET)
endfunction()
