# STAND-IN for the (uncommitted) cmake/ide/ide_config.cmake referenced by the
# dev/cmake WIP. It was never committed to any ref; this minimal version lets
# project_utils.cmake be included and post_build_config() run. Replace with the
# upstream implementation once it is available.
#
# Provides: ide_generate(<target>)

function(ide_generate PROJECT_TARGET)
	# No IDE project files are generated by this stand-in. CMake already
	# exports compile_commands.json (CMAKE_EXPORT_COMPILE_COMMANDS=ON), which
	# covers most editor tooling.
	message(STATUS "ide_generate(${PROJECT_TARGET}): stand-in, no IDE files generated")
endfunction()
