CONFIG_SPI=y
CONFIG_GPIO=y
CONFIG_CLK=y
CONFIG_JESD204=y
CONFIG_AXI_CORE=y
CONFIG_AXI_ADC_CORE=y
CONFIG_AXI_DAC_CORE=y
CONFIG_AXI_DMAC=y
CONFIG_AXI_JESD204=y
CONFIG_CLK_AXI_CLKGEN=y
CONFIG_FREQUENCY=y
CONFIG_FREQUENCY_AD9528=y
CONFIG_FREQUENCY_HMC7044=y
CONFIG_RF_TRANSCEIVER=y
CONFIG_RF_TRANSCEIVER_TALISE=y
CONFIG_ADRV9009_PROFILE_BW100=y
